CREATE TABLE IF NOT EXISTS public.canada_monthly
(
    placekey character varying(1024) COLLATE pg_catalog."default",
    parent_placekey character varying(1024) COLLATE pg_catalog."default",
    safegraph_brand_ids text COLLATE pg_catalog."default",
    location_name character varying(1024) COLLATE pg_catalog."default",
    brands text COLLATE pg_catalog."default",
    store_id text COLLATE pg_catalog."default",
    top_category text COLLATE pg_catalog."default",
    sub_category text COLLATE pg_catalog."default",
    naics_code integer,
    latitude numeric(20,15),
    longitude numeric(20,15),
    street_address text COLLATE pg_catalog."default",
    city character varying(1024) COLLATE pg_catalog."default",
    region character varying(1024) COLLATE pg_catalog."default",
    postal_code character varying(20) COLLATE pg_catalog."default",
    open_hours text COLLATE pg_catalog."default",
    category_tags text COLLATE pg_catalog."default",
    opened_on date,
    closed_on date,
    tracking_closed_since timestamp without time zone,
    websites text COLLATE pg_catalog."default",
    geometry_type text COLLATE pg_catalog."default",
    polygon_wkt text COLLATE pg_catalog."default",
    polygon_class text COLLATE pg_catalog."default",
    enclosed boolean,
    phone_number character varying(20) COLLATE pg_catalog."default",
    is_synthetic boolean,
    includes_parking_lot boolean,
    iso_country_code character varying(3) COLLATE pg_catalog."default",
    wkt_area_sq_meters numeric(20,4),
    date_range_start timestamp without time zone,
    date_range_end timestamp without time zone,
    raw_visit_counts integer,
    raw_visitor_counts integer,
    visits_by_day integer[],
    poi_cbg character varying(1024) COLLATE pg_catalog."default",
    visitor_home_cbgs jsonb,
    visitor_home_aggregation jsonb,
    visitor_daytime_cbgs jsonb,
    visitor_country_of_origin jsonb,
    distance_from_home numeric(12,2),
    median_dwell integer,
    bucketed_dwell_times jsonb,
    related_same_day_brand jsonb,
    related_same_month_brand jsonb,
    popularity_by_hour integer[],
    popularity_by_day jsonb,
    device_type character varying(255) COLLATE pg_catalog."default",
    normalized_visits_by_state_scaling numeric(20,10),
    normalized_visits_by_region_naics_visits numeric(20,10),
    normalized_visits_by_region_naics_visitors numeric(20,10),
    normalized_visits_by_total_visits numeric(20,10),
    normalized_visits_by_total_visitors numeric(20,10)
);


\copy canada_data FROM '/people_mobility_origin_dest/scripts/test.csv' WITH (FORMAT csv, HEADER);